/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValueRouteImport } from './routes/value'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as CheckoutPlaceholderRouteImport } from './routes/checkout-placeholder'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidesSaasPricingStrategyRouteImport } from './routes/guides/saas-pricing-strategy'
import { Route as GuidesSaasCostAuditRouteImport } from './routes/guides/saas-cost-audit'
import { Route as GuidesCompetitorReviewAnalysisRouteImport } from './routes/guides/competitor-review-analysis'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const ValueRoute = ValueRouteImport.update({
  id: '/value',
  path: '/value',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPlaceholderRoute = CheckoutPlaceholderRouteImport.update({
  id: '/checkout-placeholder',
  path: '/checkout-placeholder',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSaasPricingStrategyRoute =
  GuidesSaasPricingStrategyRouteImport.update({
    id: '/guides/saas-pricing-strategy',
    path: '/guides/saas-pricing-strategy',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesSaasCostAuditRoute = GuidesSaasCostAuditRouteImport.update({
  id: '/guides/saas-cost-audit',
  path: '/guides/saas-cost-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesCompetitorReviewAnalysisRoute =
  GuidesCompetitorReviewAnalysisRouteImport.update({
    id: '/guides/competitor-review-analysis',
    path: '/guides/competitor-review-analysis',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/checkout-placeholder': typeof CheckoutPlaceholderRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/value': typeof ValueRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/app': typeof AuthenticatedAppRoute
  '/guides/competitor-review-analysis': typeof GuidesCompetitorReviewAnalysisRoute
  '/guides/saas-cost-audit': typeof GuidesSaasCostAuditRoute
  '/guides/saas-pricing-strategy': typeof GuidesSaasPricingStrategyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/checkout-placeholder': typeof CheckoutPlaceholderRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/value': typeof ValueRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/app': typeof AuthenticatedAppRoute
  '/guides/competitor-review-analysis': typeof GuidesCompetitorReviewAnalysisRoute
  '/guides/saas-cost-audit': typeof GuidesSaasCostAuditRoute
  '/guides/saas-pricing-strategy': typeof GuidesSaasPricingStrategyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/checkout-placeholder': typeof CheckoutPlaceholderRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/value': typeof ValueRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/guides/competitor-review-analysis': typeof GuidesCompetitorReviewAnalysisRoute
  '/guides/saas-cost-audit': typeof GuidesSaasCostAuditRoute
  '/guides/saas-pricing-strategy': typeof GuidesSaasPricingStrategyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/checkout-placeholder'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/value'
    | '/admin'
    | '/app'
    | '/guides/competitor-review-analysis'
    | '/guides/saas-cost-audit'
    | '/guides/saas-pricing-strategy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/checkout-placeholder'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/value'
    | '/admin'
    | '/app'
    | '/guides/competitor-review-analysis'
    | '/guides/saas-cost-audit'
    | '/guides/saas-pricing-strategy'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/checkout-placeholder'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/value'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/guides/competitor-review-analysis'
    | '/guides/saas-cost-audit'
    | '/guides/saas-pricing-strategy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CheckoutPlaceholderRoute: typeof CheckoutPlaceholderRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ValueRoute: typeof ValueRoute
  GuidesCompetitorReviewAnalysisRoute: typeof GuidesCompetitorReviewAnalysisRoute
  GuidesSaasCostAuditRoute: typeof GuidesSaasCostAuditRoute
  GuidesSaasPricingStrategyRoute: typeof GuidesSaasPricingStrategyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/value': {
      id: '/value'
      path: '/value'
      fullPath: '/value'
      preLoaderRoute: typeof ValueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout-placeholder': {
      id: '/checkout-placeholder'
      path: '/checkout-placeholder'
      fullPath: '/checkout-placeholder'
      preLoaderRoute: typeof CheckoutPlaceholderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/saas-pricing-strategy': {
      id: '/guides/saas-pricing-strategy'
      path: '/guides/saas-pricing-strategy'
      fullPath: '/guides/saas-pricing-strategy'
      preLoaderRoute: typeof GuidesSaasPricingStrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/saas-cost-audit': {
      id: '/guides/saas-cost-audit'
      path: '/guides/saas-cost-audit'
      fullPath: '/guides/saas-cost-audit'
      preLoaderRoute: typeof GuidesSaasCostAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/competitor-review-analysis': {
      id: '/guides/competitor-review-analysis'
      path: '/guides/competitor-review-analysis'
      fullPath: '/guides/competitor-review-analysis'
      preLoaderRoute: typeof GuidesCompetitorReviewAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CheckoutPlaceholderRoute: CheckoutPlaceholderRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ValueRoute: ValueRoute,
  GuidesCompetitorReviewAnalysisRoute: GuidesCompetitorReviewAnalysisRoute,
  GuidesSaasCostAuditRoute: GuidesSaasCostAuditRoute,
  GuidesSaasPricingStrategyRoute: GuidesSaasPricingStrategyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
